# A plugin maded by Master
# The blocked command
Blocked Command1:
Blocked Command2:
Blocked Command3:
Blocked Command4:
Blocked Command5:
Blocked Command6:
Blocked Command7:
Blocked Command8:
Blocked Command9:
Blocked Command10:
Blocked Command11:
Blocked Command12:
Blocked Command13:
Blocked Command14:
Blocked Command15:
Blocked Command16:
Blocked Command17:
Blocked Command18:
Blocked Command19:
Blocked Command20: